/**
 * AI-powered Flipper Zero module generator.
 *
 * Uses GPT-5.4 to generate C source code for custom Flipper applications,
 * then compiles them using uFBT in a Docker sandbox.
 */

import OpenAI from "openai";
import type { ModuleBuildResult } from "@openflip/shared";
import { compileModule } from "./compiler.js";

/** Lazy-initialized OpenAI client — created on first use, after dotenv has loaded */
let _openai: OpenAI | null = null;
function getOpenAI(): OpenAI {
  if (!_openai) {
    _openai = new OpenAI({ apiKey: process.env.OPENAI_API_KEY });
  }
  return _openai;
}

const GENERATION_SYSTEM_PROMPT = `You are an expert Flipper Zero application developer.
You write C code for Flipper Zero FAP (Flipper Application Package) applications using the Flipper Zero SDK.

When asked to create a module, you must provide:
1. The application.fam manifest file
2. The main C source file(s)
3. Any additional headers if needed

## Key Flipper SDK patterns:
- Entry point: int32_t app_name_app(void* p)
- Use ViewDispatcher for UI
- Use furi_record_open("gui") for GUI access
- Use Storage API for file operations
- Use SubGhz, NFC, LFRFID APIs for protocol access
- Use NotificationApp for LED/vibration/sound
- Memory: use furi_alloc/furi_free (not malloc/free)
- Strings: use FuriString (not char arrays when possible)

## application.fam format:
App(
    appid="my_app",
    name="My App",
    apptype=FlipperAppType.EXTERNAL,
    entry_point="my_app_app",
    fap_category="Tools",
    fap_icon="icon.png",
    fap_icon_assets="assets",
    fap_author="OpenFlip AI",
    fap_version="1.0",
    fap_description="Generated by OpenFlip AI agent",
)

## Response format:
Respond with a JSON object containing:
{
  "files": {
    "application.fam": "content...",
    "my_app.c": "content...",
    "optional_header.h": "content..."
  },
  "appId": "my_app",
  "notes": "Any build or usage notes"
}

Respond ONLY with valid JSON.`;

interface GenerationResult {
  files: Record<string, string>;
  appId: string;
  notes: string;
}

/**
 * Generate a custom Flipper module from a natural language description.
 */
export async function generateModule(
  description: string,
  context?: string,
): Promise<GenerationResult> {
  const response = await getOpenAI().chat.completions.create({
    model: "gpt-4.1",
    messages: [
      { role: "system", content: GENERATION_SYSTEM_PROMPT },
      {
        role: "user",
        content: context
          ? `${description}\n\nAdditional context: ${context}`
          : description,
      },
    ],
    max_tokens: 8192,
    response_format: { type: "json_object" },
  });

  const content = response.choices[0]?.message?.content;
  if (!content) {
    throw new Error("No response from code generation model");
  }

  return JSON.parse(content) as GenerationResult;
}

/**
 * Generate and compile a module end-to-end.
 * Includes a retry loop for compilation errors.
 */
export async function generateAndCompile(
  description: string,
  maxRetries = 3,
): Promise<ModuleBuildResult> {
  let lastError = "";

  for (let attempt = 0; attempt < maxRetries; attempt++) {
    try {
      // Generate the module code
      const context =
        attempt > 0
          ? `Previous attempt failed with compilation error:\n${lastError}\n\nPlease fix the code.`
          : undefined;

      const generated = await generateModule(description, context);

      // Compile it
      const result = await compileModule(generated.appId, generated.files);

      if (result.status === "compiled") {
        return result;
      }

      lastError = result.error ?? "Unknown compilation error";
      console.log(
        `[Generator] Attempt ${attempt + 1}/${maxRetries} failed: ${lastError}`,
      );
    } catch (error) {
      lastError = error instanceof Error ? error.message : String(error);
      console.log(
        `[Generator] Attempt ${attempt + 1}/${maxRetries} error: ${lastError}`,
      );
    }
  }

  return {
    moduleId: "unknown",
    status: "failed",
    error: `Failed after ${maxRetries} attempts. Last error: ${lastError}`,
  };
}
